### ISSUE TITLE
Error: loading Sportec 2019-2020 events data

### ISSUE THREAD

**Issue by MKlaasman** [PySport/kloppy#85] opened 2021-01-14 18:04 UTC
While using events data for the 2019-2020 Bundesliga Season. I ran into an error while loading in the Sportec data. This problem does not occur for 2020-2021 season's data. 

Example code:
```
from kloppy import load_sportec_event_data
dataset = load_sportec_event_data(events_path, 
                                  matchinfo_path
                                 )
```

Error message: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-e862fa286ec2> in <module>
      3 from kloppy import SportecEventSerializer
      4 
----> 5 dataset = load_sportec_event_data(events_path, 
      6                                   matchinfo_path
      7                                  )

C:\ProgramData\Anaconda3\lib\site-packages\kloppy\helpers.py in load_sportec_event_data(event_data_filename, match_data_filename, options)
    125     ) as match_data:
    126 
--> 127         return serializer.deserialize(
    128             inputs={"event_data": event_data, "match_data": match_data},
    129             options=options,

C:\ProgramData\Anaconda3\lib\site-packages\kloppy\infra\serializers\event\sportec\serializer.py in deserialize(self, inputs, options)
    303                     )
    304                     if period_id == 1:
--> 305                         team_left = event_chain[SPORTEC_EVENT_NAME_KICKOFF][
    306                             "TeamLeft"
    307                         ]

KeyError: 'TeamLeft'
```

**Comment by schmidtfx** [comment] 2021-01-18 21:58
This is a duplicate of #84

**Closed** 2021-01-19 05:35 UTC
